---
title: "Formulaire de consentement implicite et anonyme"
author: "Le sondage pilote du projet Datagotchi : Les élections générales québécoises de 2022"
date: '2022-07-04'
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Renseignements sur le questionnaire

L’équipe de la Chaire de leadership en enseignement des sciences sociales numériques (CLESSN) de l’Université Laval est à la recherche de participants de 18 ans et plus vivant au Canada et souhaitant répondre à un sondage portant sur : les renseignements sociodémographiques, les habitudes de vie et de consommation, les préférences, les traits de personnalité, l'apparence, les attitudes, les valeurs, les allégeances ainsi que les convictions politiques pour réaliser des prédictions sur les comportements politiques des citoyens.

Le projet Datagotchi est mené par Yannick Dufresne, professeur au Département de science politique de l’Université Laval ; Simon Coulombe, professeur au Département des relations industrielles de l’Université Laval ; Sébastien Tremblay, professeur à l'école de psychologie de l'Université Laval ; Dietlind Stolle, professeure au Départment de science politique de l’Université McGill; Corentin Vande Kerckhove, assistant professeur à l’Université catholique de Louvain; Mickael Temporão, professeur associé en sciences sociales computationnelles à Science Po Bordeaux ainsi que Émilie Dionne, chercheuse à VITAM - Centre de recherche en santé durable. Le projet compte aussi sur la collaboration de Catherine Ouellet, doctorante au Département de science politique de l’Université de Toronto et de Youri Rivest, cofondateur de Synopsis. <!-- et de Youri Rivest, cofondateur de Synopsis. J'ai enlevé quelques noms, mais peut-être me confirmer qui on garde -->

Avant d’accepter de participer à ce projet, veuillez prendre le temps de lire les renseignements qui suivent.

## Nature et objectifs du projet 

Votre participation au questionnaire intitulé « Le sondage pilote du projet Datagotchi : Les élections générales québécoises de 2022» permettra de mesurer scientifiquement les facteurs qui influencent (ou non) les comportements politiques dans le cadre du développement de la plateforme Datagotchi. Datagotchi permettra aux utilisateurs d'obtenir une prédiction de leur choix de vote et d'explorer l’effet de différentes caractéristiques sur la prédiction émise par l’application (par exemple, visualiser quel serait l'effet, selon les modèles statistiques, d'être plus ou moins âgé sur votre choix de vote).

## Déroulement de la participation

Votre participation consiste à répondre à environ 121 questions et la durée du questionnaire en ligne est d’environ 25 minutes. Bien que les réponses à chacune des questions soient importantes pour la recherche, vous demeurez libre de choisir de ne pas répondre et ainsi de mettre fin à votre participation à tout moment en fermant la page de votre navigateur.

## Anonymat et conservation des données

L’information récoltée à travers Datagotchi sera uniquement rendue accessible aux chercheurs sous forme agrégée, anonymisée, et non attribuable. Le risque de réidentification d’un participant est présent, mais minime. Les données recueillies sont utilisées uniquement à des fins de recherche universitaire et ne seront jamais vendues, cédées ou transférées à des tiers à d'autres fins. 

# Attestation de consentement

Le simple fait de compléter ce questionnaire sera considéré comme l’expression implicite de votre consentement à participer au projet. 

## Renseignements supplémentaires

Si vous avez des questions sur la recherche, sur les implications de votre participation, ou pour vous retirer du projet, veuillez contacter info@clessn.com.

## Plaintes ou critiques

Si vous avez des plaintes ou des critiques relatives à votre participation à cette recherche, vous pouvez vous adresser, en toute confidentialité, au bureau de l’Ombudsman de l’Université Laval aux coordonnées suivantes:

Pavillon Alphonse-Desjardins, bureau 3320 2325, rue de l’Université  
Université Laval  
Québec (Québec) G1V 0A6  
Renseignements - Secrétariat: (418) 656-3081 Ligne sans frais: 1-866-323-2271  
Courriel: info@ombudsman.ulaval.ca

## Remerciements

Votre collaboration est précieuse pour nous permettre de réaliser cette étude. C’est pourquoi nous tenons à vous remercier pour le temps et l’attention que vous acceptez de consacrer à votre participation.

## Approbation éthique

Ce projet a été approuvé par le Comité d’éthique de la recherche de l’Université Laval : No d’approbation: 2022-181 / 27-06-2022. 
