---
title: "Implied and anonymous consent form"
author: "Datagotchi: The 2022 Quebec general election"
date: '2022-08-30'
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### The project

Université Laval's Leadership Chair in the Teaching of Digital Social Sciences (CLESSN) team invites you to participate in the Datagotchi project, a survey that predicts voting intentions through lifestyle questions in the context of the 2022 Quebec general election. Datagotchi is led by Yannick Dufresne, associate professor in the Department of Political Science at Université Laval, Simon Coulombe, associate professor in the Department of Industrial Relations at Université Laval and Catherine Ouellet, PhD student in the Department of Political Science at the University of Toronto.

### Your participation

Before agreeing to participate in this project, please take the time to read the following statements. Your participation consists of answering about 30 questions that will allow to scientifically measure the factors that may or may not influence political behaviours. Completing the questionnaire takes approximately 10 minutes. While answering every question is important to the research, you remain free to end your participation at any given time by stopping answering. At the end of the questionnaire, you will be redirected to a dashboard where you can view your profile as well as the party we believe you will probably be voting for (according to your answers) at the 2022 Quebec general election. Also, you will be able to provide your email address if you wish to be notified when the account feature is launched. This will eventually allow users to register their results and be notified when new surveys are available on Datagotchi. By the end of the survey, you will be able to discover how various factors influence the app's results; meaning you could modify each of them (age, leisure, etc.) in order to see the effect on the vote result. All questions are essential to the prediction of the Datagotchi and the Datagotchi experience. In case you prefer not to answer any of the questions, we ask you to stop your participation in the survey.

### Anonymity and data retention

The anonymous data collected through your answers may be retained for future analyses or academic research projects. It is envisioned that research results in aggregate form (that is the information obtained from the analyses in which participants' anonymous responses are grouped) may be shared with the media. The email addresses submitted by those who wish to be kept informed of the upcoming account creation feature will be kept separate from the questionnaire data in a non-reversible manner. The risk of re-identification of a participant is present but very minimal. The data collected will solely serve academic research purposes and will never be sold, assigned, or transferred to third parties for other purposes.

### Additional Information

If you have any questions about this research and/or your participation; or if you would like to withdraw from it, please contact info@datagotchi.com.

### Complaints or criticism

If you have any complaints or criticisms regarding your participation in this research; you can contact the Université Laval Ombudsman's office in complete confidentiality, through the following contact information :

**Alphonse-Desjardins Pavilion, room 3320 2325, rue de l'Université** 
Université Laval 
Quebec City, Quebec G1V 0A6 

**Information - Secretariat**: 
(418) 656-3081 

**Toll free line**: 1-866-323-2271

**Email**: info@ombudsman.ulaval.ca

### Acknowledgements

Your collaboration is valued and contributes to the success of this study. We would like to thank you for your time and interest.

### Consent attestation

Completing the upcoming questionnaire will be considered as the implied expression of your consent to participate in this project. Please note that if you are under the age of 18, your information will be excluded from the analyses, but you will still have the same experience as any other user.

* I am 18 years or older (radio button)
* I am under 18 years old (radio button)

* I have read the consent to the above questionnaire (check box)

### Ethical Approval

This project has been approved by Université Laval's Research Ethics Board: Approval № 2022-181 / 27-06-2022.
