---
title: "Formulaire de consentement implicite et anonyme"
author: "Datagotchi : Les élections générales québécoises de 2022"
date: '2022-08-30'
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Le projet

L'équipe de la Chaire de leadership en enseignement des sciences sociales numériques (CLESSN) de l'Université Laval vous invite à participer à Datagotchi, un sondage qui permet de prédire le vote lors des élections provinciales québécoises de 2022 à partir de questions liées au mode de vie. Datagotchi est mené par Yannick Dufresne, professeur au Département de science politique de l'Université Laval, Simon Coulombe, professeur au Département des relations industrielles de l'Université Laval et Catherine Ouellet, doctorante au Département de science politique de l'Université de Toronto.

### Votre participation

Avant d'accepter de participer à ce projet, veuillez prendre le temps de lire les renseignements qui suivent. Votre participation au questionnaire consiste à répondre à une trentaine de questions et permettra de mesurer scientifiquement les facteurs qui influencent (ou non) les comportements politiques. La durée du questionnaire est d'environ 10 minutes. Bien que les réponses à chacune des questions soient importantes pour la recherche, vous demeurez libre de choisir de ne pas répondre et ainsi de mettre fin à votre participation à tout moment. À la fin du questionnaire, vous serez redirigé vers un tableau de bord où vous pourrez visualiser votre profil et obtenir une prédiction de votre intention de vote pour les élections provinciales québécoises de 2022. Il vous sera possible de fournir votre adresse courriel si vous souhaitez être notifié lorsque la fonctionnalité permettant la création de compte sera disponible. Celle-ci permettra éventuellement aux utilisateurs d'enregistrer leurs résultats et d'être tenus informés lorsque de nouveaux modules seront disponibles sur Datagotchi. Vous aurez également la possibilité d'explorer l'effet des différentes variables sur la prédiction émise par l'application – c'est-à-dire, vous pourrez observer l'effet de chacune d'entre elles (âge, loisirs, etc.) sur la prédiction du choix de vote. L'ensemble des questions sont essentielles à la prédiction du Datagotchi ainsi qu'à l'expérience Datagotchi. Dans le cas où vous préférez ne pas répondre à une ou ces questions, nous vous demandons d'arrêter votre participation au sondage.

### Anonymat et conservation des données

Les données anonymes issues de vos réponses pourront être conservées pour d'autres analyses ou d'autres projets recherche universitaires ultérieurs. Il est prévu que les résultats de la recherche sous forme agrégée, c'est-à-dire des informations issues des analyses dans lesquelles les réponses anonymes des participants sont regroupées, puissent être partagés dans les médias. La liste des identifiants courriel des personnes désirant être tenues informées de la disponibilité de la fonctionnalité de création de compte sera conservée séparément des réponses aux questionnaires, et ce, de façon non réversible. Le risque de réidentification d'un participant est présent, mais il demeure minime. Les données recueillies sont utilisées uniquement à des fins de recherche universitaire et ne seront jamais vendues, cédées ou transférées à des tiers à d'autres fins.

### Renseignements supplémentaires

Si vous avez des questions sur la recherche, sur les implications de votre participation, ou pour vous retirer du projet, veuillez contacter : 
info@datagotchi.com
.

### Plaintes ou critiques

Si vous avez des plaintes ou des critiques relatives à votre participation à cette recherche, vous pouvez vous adresser, en toute confidentialité, au bureau de l'Ombudsman de l'Université Laval aux coordonnées suivantes :

**Pavillon Alphonse-Desjardins, bureau 3320 2325, rue de l'Université**
Université Laval
Québec (Québec) G1V 0A6 \

**Renseignements - Secrétariat** : 
(418) 656-3081

**Ligne sans frais** : 
1-866-323-2271

**Courriel** : 
info@ombudsman.ulaval.ca


### Remerciements

Votre collaboration est précieuse pour nous permettre de réaliser cette étude. C'est pourquoi nous tenons à vous remercier pour le temps et l'attention que vous acceptez de consacrer à votre participation.

### Attestation de consentement

Le simple fait de compléter ce questionnaire sera considéré comme l'expression implicite de votre consentement à participer au projet. Si vous êtes âgés de moins de 18 ans, vos informations seront exclues des analyses, mais vous pourrez bénéficier d'une expérience similaire aux autres utilisateurs en répondant au questionnaire et en obtenant votre résultat.

* J'ai 18 ans ou plus (bouton radio)
* J'ai moins de 18 ans (bouton radio)

* J'ai pris connaissance du consentement au questionnaire présenté ci-dessus (case à cocher)

### Approbation éthique

Ce projet a été approuvé par le Comité d'éthique de la recherche de l'Université Laval : Approbation № 2022-181 / 27-06-2022.
